name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install-Cppcheck
      run: sudo apt-get install cppcheck
    - name: Analyse
      run: cppcheck --enabel=all 3_implementation
